-- Generated by Level Director v2.9.0 on 12/6/2014 4:51:51 PM --
require("lib.LD_HelperG2")

local M = {}

-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets = {}
	assets.spriteSheetData = {}
	

	assets['ballbeach_png']={
		file = 'ballbeach.png',
		name = 'ballbeach_png',
		class = '',
		anchorX = 0,
		anchorY = 0,
		width = 64,
		height = 64,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	return assets
end -- loadAssets


-------------------------------
function M:createLevel()
-------------------------------
	local objProps = {}
	local level = {}
    local obj = nil
	
	if (application.LevelDirectorSettings.viewGroup == nil) then
		level.view = display.newGroup() 
	else
		level.view = application.LevelDirectorSettings.viewGroup
	end
	
	level.view.anchorChildren =false 
	
	display.setDefault( 'background',  105 / 255, 105 / 255, 105 / 255, 255 / 255)
	display.setDefault( "anchorX", 0 )
	display.setDefault( "anchorY", 0 )	
	display.setDrawMode("wireframe",false)
	
	level.name = 'Level2' 
	
	-- Load Assets
	level.assets = self:loadAssets()

	-- Physics properties
	physics.setGravity(0,9.80000019073486) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	
	level.parallaxEnabled = false
	
	-- Layers
	level.layers = {} 
	---- Layer 1 ----
	level.layers['Layer 1'] = {} 
	level.layers['Layer 1'].view = display.newGroup() 
	level.layers['Layer 1'].name = 'Layer 1' 
	
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed = {x = 0, y = 0}
		level.layers['Layer 1'].repeated = false
		level.layers['Layer 1'].cullingMethod = 0
	else
		level.layers['Layer 1'].cullingMethod = 0 
	end
	
	level.layers['Layer 1'].objects = {} 

	objProps = 
	{
		name 	= 'img_1', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 272,
		y		= 160,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_2', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 704,
		y		= 112,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_3', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 384,
		y		= 448,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_4', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 544,
		y		= 272,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_5', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 720,
		y		= 496,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_6', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 144,
		y		= 416,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_7', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 144,
		y		= 208,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_8', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 144,
		y		= 0,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_9', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 32,
		y		= 128,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_10', 
		objType = 'LDObjectImage',
		class = '',
		width	= 64,
		height	= 64,
		x		= 336,
		y		= 48,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= 'ballbeach_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['Layer 1'],objProps, level.assets) 
	
	LD_Helper:instance():insertLayer(level,level.layers['Layer 1'])
	
	--level.ldVersion = 2.9.0	-- Level Director Version
	
	-- Parallax (after layers)
	level.canvasWidth = 1334
	level.canvasHeight = 750
	
	if level.parallaxEnabled then
		level.parallaxInfinite = false
		level.parallaxDamping = 1
		LD_Helper:instance():createParallax(level)
	end

	
	
	return level
end -- createLevel

return M

